name: Build and deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: BotijaReg
        password: ${{secrets.REGISTRYPASSWORD}}
        repository: botija
        tags: latest,${{github.run_id}}
    
  
    - name: Azure Login and ACI restart
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az login --service-principal -u http://BotijaSPN -p ${{secrets.SPNSECRET}} --tenant 5b973f99-77df-4beb-b27d-aa0c70b8482c
          az container restart -n botija -g BotijaRG