name: Build
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . -t botijatest && docker run -t botijatest -e DISCORD_TOKEN=${{secrets.DISCORDTESTTOKEN}} -e SQL_SERVER=botijasql.database.windows.net -e SQL_DB=BotijaDB -e SQL_USER=dbWSS -e SQL_PASS=${{secrets.SQLPASS}}"